flowchart TD
    QGHtzW7MvDySRoxTS57Wr["kfc疯狂星期四"]
    Ny5QjgOcDuE77g3vsTU3p["v我50"]
    b4wZeVHo0n6NiLv7nKkLZ{"有群u？"}
    pPn1kn_WRFnyiLvbKTmBB["哭哭"]
    QGHtzW7MvDySRoxTS57Wr --> b4wZeVHo0n6NiLv7nKkLZ
    b4wZeVHo0n6NiLv7nKkLZ -->|是| Ny5QjgOcDuE77g3vsTU3p
    b4wZeVHo0n6NiLv7nKkLZ -->|否| pPn1kn_WRFnyiLvbKTmBB
    pTkFVKXU4VuPd9bq9gjbl --> QGHtzW7MvDySRoxTS57Wr
classDef c1 stroke:#1e1e1e
class QGHtzW7MvDySRoxTS57Wr c1
class Ny5QjgOcDuE77g3vsTU3p c1
class b4wZeVHo0n6NiLv7nKkLZ c1
class pPn1kn_WRFnyiLvbKTmBB c1
linkStyle 0 stroke:#1e1e1e
linkStyle 1 stroke:#1e1e1e
linkStyle 2 stroke:#1e1e1e
linkStyle 3 stroke:#1e1e1e
