flowchart TD
    QGHtzW7MvDySRoxTS57Wr["kfc疯狂星期四"]
    Ny5QjgOcDuE77g3vsTU3p["v我50"]
    b4wZeVHo0n6NiLv7nKkLZ{"有群u？"}
    pPn1kn_WRFnyiLvbKTmBB["哭哭"]
    QGHtzW7MvDySRoxTS57Wr --> b4wZeVHo0n6NiLv7nKkLZ
    b4wZeVHo0n6NiLv7nKkLZ -->|是| Ny5QjgOcDuE77g3vsTU3p
    b4wZeVHo0n6NiLv7nKkLZ -->|否| pPn1kn_WRFnyiLvbKTmBB
